import type { Metadata } from 'next';
import { Heebo } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';

const heebo = Heebo({
	subsets: ['hebrew'],
	weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Bapoop',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="he" dir="rtl">
			<body className={heebo.className}>
				<div className="mobile-container">{children}</div>
			</body>
		</html>
	);
}
